#!/usr/bin/env python3
"""
Build the Kaggle kernel that trains the PINK CGCNN on a GPU.
============================================================

    python kaggle/build_kernel.py        # writes kaggle/build/

WHY KAGGLE AND NOT COLAB
------------------------
Colab has no API for hosted runtimes - a human has to sit there and click. Kaggle
Notebooks expose a real one (`kaggle kernels push / status / output`), so the
whole loop runs from a terminal: push the job, poll it, pull the results. Same
free T4, plus a P100 option and a 30 GPU-hour weekly quota.

Like the Colab notebook, the kernel is GENERATED from the live source files
rather than checked in, because it has to carry a copy of cgcnn_scratch/ and
scripts/ - Kaggle cannot reach this private repo. A checked-in copy would go
stale and silently train with the wrong featuriser.

WHERE THINGS RUN
----------------
Kaggle treats /kaggle/working as the kernel's OUTPUT: everything left there is
captured and downloadable. That makes it the wrong place to work, because the
240 MB graph cache would be captured too and we would download it for nothing.
So the code and the dataset live in /kaggle/temp (scratch, discarded), and only
results/ is copied into /kaggle/working at the end.
"""

import base64
import io
import json
import os
import zipfile

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_DIR = os.path.join(PROJECT_ROOT, "kaggle", "build")

# Kaggle derives the real URL slug from the TITLE, not from the id we send: a
# title of "PINK CGCNN - elastic moduli on matbench" silently created the kernel
# at .../pink-cgcnn-elastic-moduli-on-matbench while we were asking after
# .../pink-cgcnn-train, so every status and output call 404'd. Keep the two in
# lockstep by deriving the slug from the title rather than setting it by hand.
KERNEL_TITLE = "PINK CGCNN GPU run"
KERNEL_SLUG = KERNEL_TITLE.lower().replace(" ", "-")

BUNDLE = [
    "cgcnn_scratch/__init__.py",
    "cgcnn_scratch/data.py",
    "cgcnn_scratch/model.py",
    "scripts/01b_prepare_full_dataset.py",
    "scripts/02_train.py",
    "scripts/03_evaluate.py",
    "scripts/04_predict_moduli.py",
    "scripts/05_ensemble.py",
    "data/atom_init.json",
]


def build_bundle_b64():
    """Zip the source files and base64 them so the kernel is self-contained."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for relative in BUNDLE:
            path = os.path.join(PROJECT_ROOT, relative)
            if not os.path.exists(path):
                raise SystemExit(f"missing bundle file: {relative}")
            archive.write(path, relative)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


KERNEL_TEMPLATE = '''#!/usr/bin/env python3
"""
PINK / CGCNN - train bulk and shear modulus models on the full matbench set.

Generated by kaggle/build_kernel.py - do not edit here, edit the generator.

Trains three ensemble members per target (six models) on all 10,987 matbench
elastic crystals, scores them individually and as an ensemble, and leaves
everything in /kaggle/working/results for download.
"""

import base64
import io
import os
import shutil
import subprocess
import sys
import time
import zipfile

# Work in /kaggle/temp: it is scratch and is NOT captured as kernel output. Only
# results/ gets copied to /kaggle/working at the end, so we do not download the
# 240 MB graph cache for nothing.
WORK = "/kaggle/temp/pink"
OUT = "/kaggle/working"

BUNDLE_B64 = "{bundle_b64}"


def run(args, cwd=WORK):
    """Run a step, streaming output live, and abort the kernel on failure.

    -u because Python block-buffers stdout when it is not a terminal, and a
    200-epoch run prints only ~2 KB - without it the log stays empty until each
    model finishes and a healthy run looks identical to a hung one.
    """
    print("$", " ".join(args), flush=True)
    result = subprocess.run([sys.executable, "-u"] + args, cwd=cwd)
    if result.returncode:
        raise SystemExit(f"FAILED (exit {{result.returncode}}): {{' '.join(args)}}")


print("=" * 62, flush=True)
print("ENVIRONMENT", flush=True)
print("=" * 62, flush=True)
import torch
print("torch      :", torch.__version__, flush=True)
print("cuda avail :", torch.cuda.is_available(), flush=True)
if torch.cuda.is_available():
    print("gpu        :", torch.cuda.get_device_name(0), flush=True)
else:
    raise SystemExit("No GPU. Enable the accelerator in kernel-metadata.json.")

# matminer pulls the matbench datasets; pymatgen does the crystal handling.
# Kaggle preinstalls neither at a usable version, and this needs internet
# enabled on the kernel (which requires a phone-verified Kaggle account).
print("\\ninstalling pymatgen + matminer...", flush=True)
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "pymatgen", "matminer"], check=True)

# --- Unpack the embedded source -------------------------------------------
os.makedirs(WORK, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode(BUNDLE_B64))) as archive:
    archive.extractall(WORK)
print("\\nunpacked:", sorted(os.listdir(WORK)), flush=True)

# --- Build the 10,987-crystal training set --------------------------------
# --skip-match: the provenance matching needs the 1,213 local CIFs, which are
# not uploaded. That step runs back on the laptop.
print("\\n" + "=" * 62, flush=True)
print("BUILDING DATASET", flush=True)
print("=" * 62, flush=True)
run(["scripts/01b_prepare_full_dataset.py", "--skip-match"])

# --- Train six models -----------------------------------------------------
# --seed varies (weight init); --split-seed is PINNED so every member shares
# one train/val/test split. Otherwise the ensemble's test score would be
# measured partly on data some members trained on.
# --num-workers 0: the graphs are already in RAM, so workers would only add
# per-batch pickling across a process boundary.
COMMON = ["--data-dir", "data_full", "--batch-size", "128", "--lr", "0.01",
          "--atom-fea-len", "64", "--h-fea-len", "128", "--n-h", "1",
          "--split-seed", "42", "--scheduler", "cosine", "--epochs", "200",
          "--device", "cuda", "--num-workers", "0"]

print("\\n" + "=" * 62, flush=True)
print("TRAINING", flush=True)
print("=" * 62, flush=True)
start = time.time()
for target in ("K_VRH", "G_VRH"):
    for tag, seed, n_conv in ((target + "_full", "42", "3"),
                              (target + "_s1", "1", "4"),
                              (target + "_s2", "2", "3")):
        t0 = time.time()
        print("\\n" + "=" * 62, flush=True)
        print(f"{{tag}}  (seed {{seed}}, n_conv {{n_conv}})"
              f"   [{{(time.time() - start) / 60:.0f}} min elapsed]", flush=True)
        print("=" * 62, flush=True)
        run(["scripts/02_train.py", "--target", target, "--tag", tag,
             "--seed", seed, "--n-conv", n_conv] + COMMON)
        print(f">>> {{tag}} done in {{(time.time() - t0) / 60:.1f}} min", flush=True)

print(f"\\nAll six models trained in {{(time.time() - start) / 60:.0f}} min", flush=True)

# --- Score, alone and as an ensemble --------------------------------------
print("\\n" + "=" * 62, flush=True)
print("SCORING", flush=True)
print("=" * 62, flush=True)
for target in ("K_VRH", "G_VRH"):
    run(["scripts/03_evaluate.py", "--target", target,
         "--data-dir", "data_full", "--tag", target + "_full"])
    run(["scripts/05_ensemble.py", "--target", target, "--data-dir", "data_full",
         "--tags", f"{{target}}_full,{{target}}_s1,{{target}}_s2"])

# --- Hand the results back ------------------------------------------------
# Checkpoints are serialised on CPU by 02_train.py, so these load on a laptop
# with no CUDA.
shutil.copytree(os.path.join(WORK, "results"), os.path.join(OUT, "results"),
                dirs_exist_ok=True)
# labels.csv is small and makes the results self-describing; graphs.pt is not
# copied - it is 240 MB and trivially regenerated.
shutil.copy(os.path.join(WORK, "data_full", "labels.csv"),
            os.path.join(OUT, "matbench_labels.csv"))

print("\\n" + "=" * 62, flush=True)
print("OUTPUT", flush=True)
print("=" * 62, flush=True)
for root, _, files in os.walk(os.path.join(OUT, "results")):
    for name in sorted(files):
        path = os.path.join(root, name)
        print(f"  {{os.path.getsize(path) / 1e3:9.1f}} KB  {{name}}", flush=True)
print("\\nPIPELINE COMPLETE", flush=True)
'''


def main():
    os.makedirs(BUILD_DIR, exist_ok=True)

    # Read the authenticated username so the kernel id is right for whoever
    # runs this, rather than hard-coding one account.
    from kaggle.api.kaggle_api_extended import KaggleApi
    api = KaggleApi()
    api.authenticate()
    username = api.config_values.get("username")
    if not username:
        raise SystemExit("Could not determine the Kaggle username.")

    kernel_path = os.path.join(BUILD_DIR, "pink_cgcnn.py")
    with open(kernel_path, "w") as fh:
        fh.write(KERNEL_TEMPLATE.format(bundle_b64=build_bundle_b64()))

    metadata = {
        "id": f"{username}/{KERNEL_SLUG}",
        "title": KERNEL_TITLE,
        "code_file": "pink_cgcnn.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        # The GPU is the entire point of moving off the laptop.
        #
        # enable_gpu ALONE IS NOT ENOUGH on this API version - it is accepted
        # and silently ignored, and the kernel lands on the CPU image (the run
        # that taught us this reported "torch 2.10.0+cpu, cuda avail: False").
        # machine_shape is the field that actually attaches a device.
        # Allowed: NvidiaTeslaT4, NvidiaTeslaP100, Tpu1VmV38.
        # P100 over T4: ~9.3 vs ~8.1 TFLOPS FP32, and this model trains in FP32.
        "enable_gpu": True,
        "machine_shape": "NvidiaTeslaP100",
        # Un-pin the docker image. Kaggle pinned this kernel to the exact image
        # sha of its FIRST run - which was a CPU run - and every later push
        # inherited that pin, so the container came back CPU-only no matter what
        # accelerator we asked for. "latest" lets Kaggle pick the image that
        # matches the requested machine shape.
        "docker_image_pinning_type": "latest",
        # Needed to pip install pymatgen/matminer and to download matbench.
        # Kaggle only allows internet on kernels for phone-verified accounts.
        "enable_internet": True,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    with open(os.path.join(BUILD_DIR, "kernel-metadata.json"), "w") as fh:
        json.dump(metadata, fh, indent=2)

    size_kb = os.path.getsize(kernel_path) / 1024
    print(f"Built kernel for {username}/{KERNEL_SLUG}")
    print(f"  {kernel_path}  ({size_kb:.0f} KB)")
    print(f"  {BUILD_DIR}/kernel-metadata.json")
    print("\nPush and watch it with:")
    print("  python kaggle/run_kernel.py")


if __name__ == "__main__":
    main()
